language: go

sudo: required

env:
  - GO111MODULE=on

services:
  - docker
  - mongodb

go:
  - "1.12.x"


stages:
  - test
  - build
  - deploy

jobs:
  include:
    - stage: test
      before_script:
        - sleep 15
      script: make test
    - stage: build
      script: make docker-push
    - stage: deploy
      script:
        - envsubst --help ##testing if it works
        - make create-kube-config
        - cat ~/.kube/config
        - make install-kubectl
        - make blue-green
