language: go

sudo: required

env:
  - GO111MODULE=on

services:
  - docker
  - mongo

go:
  - "1.12.x"

before_script:
  - sleep 60
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script: make ci