version: '3'
services:
  fortune-app-backend:
    build: .
    environment:
      MONGO_ADDR: "mongodb://fortune_backend_mongo:27017/fortune-messages"
    ports:
      - 4001:4000
      
  fortune_backend_mongo:
    image: mongo